// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Handwritten extension of the generated Project class.
 *
 * Adds uploadImage() — a REST-based operation that cannot be generated by the
 * domain-map pipeline because BatchCreateScreens is a private endpoint with no
 * corresponding MCP tool in tools-manifest.json.
 *
 * The generated Project class is re-exported from this module, so consumers
 * import a single Project class that includes both generated and handwritten
 * methods.
 */

import { Project as GeneratedProject } from '../generated/src/project.js';
import { Screen } from '../generated/src/screen.js';
import { StitchError, StitchErrorCode } from './spec/errors.js';
import * as cheerio from 'cheerio';
import { DownloadAssetsHandler } from './download-handler.js';
import { DownloadAssetsInputSchema, DownloadedScreenTrace } from './spec/download.js';
import {
  UploadImageInputSchema,
  type UploadImageInput,
} from './spec/upload.js';
import { UploadImageHandler } from './upload-handler.js';

interface ExtractionRule {
  target: 'customColor' | 'headlineFont' | 'roundness';
  matches: (property: string, value: string) => boolean;
  extract: (value: string) => string | undefined;
}

const EXTRACTION_RULES: ExtractionRule[] = [
  {
    target: 'customColor',
    matches: (prop, val) => prop.includes('color') && val.startsWith('#') && val.length === 7,
    extract: (val) => val,
  },
  {
    target: 'headlineFont',
    matches: (prop, _) => prop.includes('font-family'),
    extract: (val) => {
      let font = val.split(',')[0].trim();
      if (font.startsWith("'") || font.startsWith('"')) font = font.slice(1);
      if (font.endsWith("'") || font.endsWith('"')) font = font.slice(0, -1);
      return font;
    },
  },
  {
    target: 'roundness',
    matches: (prop, _) => prop.includes('border-radius'),
    extract: (val) => {
      if (val.endsWith('px')) {
        const px = parseInt(val.slice(0, -2));
        if (px >= 8) return "ROUND_EIGHT";
        if (px >= 4) return "ROUND_FOUR";
      }
      return undefined;
    },
  },
];

export class Project extends GeneratedProject {
  /**
   * Upload an image file to the project and create a new Screen from it.
   *
   * WHY THIS IS NOT GENERATED:
   *   BatchCreateScreens is a private REST endpoint — it has no MCP tool
   *   in tools-manifest.json. It also requires reading a file from disk and
   *   base64-encoding it, which the codegen arg-routing model cannot express.
   *
   * @param filePath - Absolute or relative path to the image (PNG, JPG, JPEG, WEBP).
   * @param opts - Optional screen title and createScreenInstances flag.
   * @returns An array of Screen objects created from the upload.
   * @throws {StitchError} on file not found, unsupported format, or upload failure.
   *
   * @example
   * const [screen] = await project.uploadImage('./mockup.png', { title: 'Home Screen' });
   * const html = await screen.getHtml();
   */
  async uploadImage(
    filePath: string,
    opts?: Partial<Omit<UploadImageInput, 'filePath'>>,
  ): Promise<Screen[]> {
    const input = UploadImageInputSchema.parse({ filePath, ...opts });
    const handler = new UploadImageHandler(this['client']);
    const result = await handler.execute(this.projectId, input);

    if (!result.success) {
      throw new StitchError({
        code: result.error.code === 'FILE_NOT_FOUND'
          ? 'NOT_FOUND'
          : result.error.code === 'AUTH_FAILED'
          ? 'AUTH_FAILED'
          : 'UNKNOWN_ERROR',
        message: result.error.message,
        recoverable: result.error.recoverable,
      });
    }

    return result.screens;
  }

  /**
   * Parses HTML of a screen to extract theme tokens.
   * Maps them to the expected Stitch API Theme schema.
   *
   * @param screenId - The ID of the screen to analyze.
   * @returns A partial theme object.
   */
  async inferTheme(screenId: string): Promise<any> {
    const screens = await this.screens();
    const screen = screens.find(s => s.id === screenId);
    if (!screen) {
      throw new Error(`Screen ${screenId} not found in project`);
    }
    const htmlUrl = await screen.getHtml();
    console.log(`[DEBUG] inferTheme: htmlUrl for screen ${screenId} is "${htmlUrl}"`);
    console.log(`[DEBUG] inferTheme: screen data:`, JSON.stringify((screen as any).data));

    if (!htmlUrl) {
      throw new Error(`Screen ${screenId} has no HTML URL`);
    }

    const html = await fetch(htmlUrl).then((r: any) => r.text());
    const $ = cheerio.load(html);

    const stylesText = $('style').text();
    const declarations = stylesText.split(';').map(s => s.trim());
    const result: Record<string, string | undefined> = {};

    for (const decl of declarations) {
      const parts = decl.split(':');
      if (parts.length !== 2) continue;
      const property = parts[0].trim();
      const value = parts[1].trim();

      for (const rule of EXTRACTION_RULES) {
        if (rule.matches(property, value)) {
          const extracted = rule.extract(value);
          if (extracted !== undefined) {
            result[rule.target] = extracted;
          }
        }
      }
    }

    return {
      customColor: result.customColor,
      headlineFont: result.headlineFont,
      roundness: result.roundness
    };
  }

  /**
   * Injects design system tokens into a prompt to guide generation.
   *
   * @param prompt - The original user prompt.
   * @param theme - The theme tokens to inject.
   * @returns The enhanced prompt.
   */
  themePrompt(prompt: string, theme: any): string {
    let themeInstructions = "\n\nUse the following design system tokens strictly:\n";
    
    if (theme.customColor) {
      themeInstructions += `- Primary Color: ${theme.customColor}\n`;
    }
    if (theme.headlineFont) {
      themeInstructions += `- Typography: Use ${theme.headlineFont} for headings and body text.\n`;
    }
    if (theme.roundness) {
      themeInstructions += `- Roundness: Use ${theme.roundness} style for corners.\n`;
    }

    return `${prompt}${themeInstructions}`;
  }

  /**
   * Orchestrates the API dance for creating/updating design systems.
   * If a design system exists for the project, updates it.
   * Otherwise, creates a new one.
   *
   * @param theme - The theme tokens to sync.
   * @returns The DesignSystem handle.
   */
  async syncTheme(theme: any): Promise<any> {
    const list = await (this as any).listDesignSystems();
    
    if (list.length > 0) {
      const existing = list[0];
      return await existing.update({ theme });
    } else {
      return await (this as any).createDesignSystem({ theme });
    }
  }

  /**
   * Downloads all screens and their referenced assets to a local directory.
   * Rewrites URLs in HTML to be self-contained.
   *
   * @param outputDir - The directory to save assets to.
   */
  async downloadAssets(
    outputDir: string,
    opts?: { fileMode?: number; tempDir?: string; assetsSubdir?: string },
  ): Promise<DownloadedScreenTrace[]> {
    const handler = new DownloadAssetsHandler((this as any).client);
    const input = DownloadAssetsInputSchema.parse({
      projectId: (this as any).projectId,
      outputDir,
      ...opts,
    });
    const result = await handler.execute(input);
    if (!result.success) {
      let code: StitchErrorCode = 'UNKNOWN_ERROR';
      switch (result.error.code) {
        case 'PROJECT_NOT_FOUND':
          code = 'NOT_FOUND';
          break;
        case 'FETCH_FAILED':
          code = 'NETWORK_ERROR';
          break;
        case 'PATH_TRAVERSAL_ATTEMPT':
          code = 'VALIDATION_ERROR';
          break;
      }
      throw new StitchError({
        code,
        message: result.error.message,
        recoverable: result.error.recoverable,
      });
    }
    return result.downloadedScreens;
  }

  /**
   * Creates a new session in the project using the direct REST API.
   * Spike: Exploratory REST support.
   */
  async createSessionREST(prompt: string, deviceType?: string): Promise<any> {
    try {
      const body: Record<string, any> = { prompt };
      if (deviceType) body.deviceType = deviceType;
      
      return await this['client'].httpPost<any>(`projects/${this.projectId}/sessions`, body);
    } catch (error) {
      throw StitchError.fromUnknown(error);
    }
  }
}
