#!/usr/bin/env bun
/**
 * Stage 3: Generate SDK
 *
 * Reads tools-manifest.json + domain-map.json and emits TypeScript
 * files into core/generated/src/. Deterministic — no LLM involved.
 *
 * Validates the binding IR (domain-map) against its Zod schema and
 * verifies response projections against the tool output schemas.
 *
 * Updates the generated section of stitch-sdk.lock.
 *
 * Usage: bun scripts/generate-sdk.ts
 */

import { resolve } from "node:path";
import { createHash } from "node:crypto";
import { readdirSync, mkdirSync, rmSync, existsSync, readFileSync } from "node:fs";
import { DomainMap, type ProjectionStep, type Binding, type ArgSpec } from "../core/generated/ir-schema.js";

const ROOT_DIR = resolve(import.meta.dir, "..");
const MANIFEST_PATH = resolve(ROOT_DIR, "core/generated/tools-manifest.json");
const DOMAIN_MAP_PATH = resolve(ROOT_DIR, "core/generated/domain-map.json");
const GENERATED_DIR = resolve(ROOT_DIR, "core/generated/src");
const LOCK_PATH = resolve(ROOT_DIR, "core/generated/stitch-sdk.lock");

interface Tool {
  name: string;
  description?: string;
  inputSchema?: {
    properties?: Record<string, any>;
    required?: string[];
  };
  outputSchema?: any;
}

function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function hashDirectory(dir: string): string {
  if (!existsSync(dir)) return sha256("");
  const hash = createHash("sha256");
  const files = getAllFiles(dir).sort();
  for (const file of files) {
    hash.update(file);
    hash.update(readFileSync(file));
  }
  return hash.digest("hex");
}

function getAllFiles(dir: string): string[] {
  const results: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...getAllFiles(full));
    } else {
      results.push(full);
    }
  }
  return results;
}

function fileHeader(manifestHash: string, domainMapHash: string): string {
  return `/**
 * AUTO-GENERATED by scripts/generate-sdk.ts
 * DO NOT EDIT — changes will be overwritten.
 *
 * Source: tools-manifest.json (sha256:${manifestHash.slice(0, 12)}...)
 *         domain-map.json     (sha256:${domainMapHash.slice(0, 12)}...)
 * Generated: ${new Date().toISOString()}
 */

`;
}

// ── Output Schema Validation ──────────────────────────────────

/**
 * Resolve a $ref in a JSON Schema, returning the referenced schema.
 */
function resolveRef(schema: any, ref: string): any {
  // $ref format: "#/$defs/Foo"
  const parts = ref.replace("#/", "").split("/");
  let node = schema;
  for (const p of parts) {
    node = node?.[p];
  }
  return node;
}

/**
 * Validate that a projection path resolves against a JSON Schema.
 * Returns the schema node at the end of the projection, or throws
 * with a diagnostic error if a property doesn't exist.
 */
function validateProjection(
  projection: ProjectionStep[],
  outputSchema: any,
  bindingLabel: string,
): void {
  if (!outputSchema) return; // No schema to validate against

  let currentSchema = outputSchema;
  const rootSchema = outputSchema;

  for (let i = 0; i < projection.length; i++) {
    const step = projection[i];

    // Resolve $ref if present
    if (currentSchema?.$ref) {
      currentSchema = resolveRef(rootSchema, currentSchema.$ref);
    }

    // If current is an array schema and we're using each/index, unwrap items
    if (currentSchema?.type === "array" && currentSchema?.items) {
      currentSchema = currentSchema.items;
      if (currentSchema?.$ref) {
        currentSchema = resolveRef(rootSchema, currentSchema.$ref);
      }
    }

    const props = currentSchema?.properties;
    if (!props) {
      // Can't validate further (schema is too loose)
      return;
    }

    if (!(step.prop in props)) {
      const available = Object.keys(props).join(", ");
      throw new Error(
        `❌ Binding "${bindingLabel}" projection step ${i + 1}: ` +
        `property "${step.prop}" not found in outputSchema.\n` +
        `   Available properties: ${available}\n` +
        `   Fix: check the projection in domain-map.json for this binding.`
      );
    }

    // Advance to the property's schema
    currentSchema = props[step.prop];

    // Resolve $ref
    if (currentSchema?.$ref) {
      currentSchema = resolveRef(rootSchema, currentSchema.$ref);
    }

    // If accessing array items (index or each), unwrap to items schema
    if ((step.index !== undefined || step.each) && currentSchema?.type === "array" && currentSchema?.items) {
      currentSchema = currentSchema.items;
      if (currentSchema?.$ref) {
        currentSchema = resolveRef(rootSchema, currentSchema.$ref);
      }
    }
  }
}

// ── Projection Code Emission ──────────────────────────────────

/**
 * Emit TypeScript code for a projection path.
 * 
 * Replaces the old string-parsing functions (generateExtractExpression,
 * generateGlobExtract). Walks the ProjectionStep[] array and emits
 * property access, [index], or .flatMap() for each step.
 */
function emitProjection(steps: ProjectionStep[], rawVar: string = "raw"): string {
  if (steps.length === 0) return rawVar;

  // Check if any step uses 'each' (flatMap pattern)
  const hasEach = steps.some(s => s.each);

  if (hasEach) {
    return emitFlatMapProjection(steps, rawVar);
  }

  // Simple chain: raw.prop1[0].prop2.prop3
  let code = rawVar;
  for (const step of steps) {
    code += `.${step.prop}`;
    if (step.index !== undefined) {
      code += `[${step.index}]`;
    }
  }
  return code;
}

/**
 * Emit flatMap chain for projections with 'each' steps.
 * e.g. [each:outputComponents, prop:design, each:screens] →
 *   (raw.outputComponents || []).flatMap((a: any) => a.design.screens || [])
 */
function emitFlatMapProjection(steps: ProjectionStep[], rawVar: string): string {
  let code = rawVar;
  let tempVar = "a";
  let i = 0;

  while (i < steps.length) {
    const step = steps[i];
    code += `.${step.prop}`;

    if (step.each) {
      // Collect subsequent non-each steps to chain onto the flatMap var
      code = `(${code} || [])`;
      const innerSteps: string[] = [];
      i++;
      while (i < steps.length && !steps[i].each) {
        innerSteps.push(`.${steps[i].prop}`);
        if (steps[i].index !== undefined) {
          innerSteps.push(`[${steps[i].index}]`);
        }
        i++;
      }

      // If there are more 'each' steps after inner steps, continue flatMap chain
      if (i < steps.length && steps[i].each) {
        const innerPath = innerSteps.join("") + `.${steps[i].prop}`;
        code = `${code}.flatMap((${tempVar}: any) => ${tempVar}${innerPath} || [])`;
        tempVar = String.fromCharCode(tempVar.charCodeAt(0) + 1);
        i++;
      } else if (innerSteps.length > 0) {
        // Terminal: flatMap with inner path
        const innerPath = innerSteps.join("");
        code = `${code}.flatMap((${tempVar}: any) => ${tempVar}${innerPath} || [])`;
        tempVar = String.fromCharCode(tempVar.charCodeAt(0) + 1);
      }
    } else if (step.index !== undefined) {
      code += `[${step.index}]`;
      i++;
    } else {
      i++;
    }
  }

  return code;
}

/**
 * Emit TypeScript code for a cache check projection.
 * e.g. [screenshot, downloadUrl] → this.data?.screenshot?.downloadUrl
 */
function emitCacheProjection(steps: ProjectionStep[]): string {
  let code = "this.data";
  for (const step of steps) {
    code += `?.${step.prop}`;
  }
  return code;
}

// ── Param Type Generation ─────────────────────────────────────

/**
 * Convert a tool's inputSchema properties to TypeScript param types.
 * Types are derived from the manifest inputSchema, not hardcoded in domain-map.
 */
function generateParamType(tool: Tool, args: Record<string, ArgSpec>): string {
  const params: string[] = [];
  for (const [name, spec] of Object.entries(args)) {
    if (spec.from !== "param") continue;
    const paramName = spec.rename || name;
    const toolProp = tool.inputSchema?.properties?.[name];
    const tsType = jsonSchemaToTs(toolProp);
    const optional = spec.optional ? "?" : "";
    params.push(`${paramName}${optional}: ${tsType}`);
  }
  return params.join(", ");
}

/**
 * Convert JSON Schema type to TypeScript type.
 */
function jsonSchemaToTs(prop: any): string {
  if (!prop) return "any";
  if (prop.enum) {
    return prop.enum.map((v: string) => `"${v}"`).join(" | ");
  }
  switch (prop.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "array":
      if (prop.items) return `${jsonSchemaToTs(prop.items)}[]`;
      return "any[]";
    case "object": return "any";
    default: return "any";
  }
}

// ── Arg Object Generation ─────────────────────────────────────

function generateArgsObject(args: Record<string, ArgSpec>): string {
  const entries: string[] = [];
  for (const [name, spec] of Object.entries(args)) {
    if (spec.from === "self") {
      entries.push(`${name}: this.${name}`);
    } else if (spec.from === "selfArray") {
      const field = spec.field || name;
      entries.push(`${name}: [this.${field}]`);
    } else if (spec.from === "param") {
      const paramName = spec.rename || name;
      entries.push(name === paramName ? name : `${name}: ${paramName}`);
    } else if (spec.from === "computed") {
      const templateStr = spec.template || "";
      const interpolated = templateStr.replace(
        /\{(\w+)\}/g,
        (_, key) => {
          const argSpec = args[key];
          if (argSpec?.from === "self" || argSpec?.from === "selfArray") return `\${this.${key}}`;
          return `\${${argSpec?.from === "param" && argSpec?.rename ? argSpec.rename : key}}`;
        }
      );
      entries.push(`${name}: \`${interpolated}\``);
    }
  }
  return `{ ${entries.join(", ")} }`;
}

// ── Return Expression Generation ──────────────────────────────

function generateReturnExpression(
  binding: Binding,
  className: string,
  domainMap: ReturnType<typeof DomainMap.parse>,
): string {
  const projection = binding.returns.projection;
  const projectionExpr = emitProjection(projection);

  if (binding.returns.class) {
    const childClass = domainMap.classes[binding.returns.class];
    const parentField = childClass?.parentField;

    if (binding.returns.array) {
      const itemExpr = parentField
        ? `{ ...item, ${parentField}: this.${parentField} }`
        : "item";
      // Null-safe: default to empty array if projection yields undefined
      return `(${projectionExpr} || []).map((item: any) => new ${binding.returns.class}(this.client, ${itemExpr}))`;
    }

    const dataExpr = parentField
      ? `{ ...${projectionExpr}, ${parentField}: this.${parentField} }`
      : projectionExpr;
    return `new ${binding.returns.class}(this.client, ${dataExpr})`;
  }

  return `${projectionExpr} || ""`;
}

// ── Main ──────────────────────────────────────────────────────

async function main() {
  console.log("📖 Reading inputs...");

  const manifestContent = await Bun.file(MANIFEST_PATH).text();
  const domainMapContent = await Bun.file(DOMAIN_MAP_PATH).text();

  const manifest: Tool[] = JSON.parse(manifestContent);
  const domainMapRaw = JSON.parse(domainMapContent);

  // ── Validate binding IR against Zod schema ──
  console.log("🔍 Validating binding IR...");
  const parseResult = DomainMap.safeParse(domainMapRaw);
  if (!parseResult.success) {
    console.error("❌ domain-map.json failed IR schema validation:");
    for (const issue of parseResult.error.issues) {
      console.error(`   ${issue.path.join(".")}: ${issue.message}`);
    }
    process.exit(1);
  }
  const domainMap = parseResult.data;
  console.log("  ✓ IR schema valid");

  // ── Validate projections against output schemas ──
  console.log("🔍 Validating projections against output schemas...");
  let projectionErrors = 0;
  for (const binding of domainMap.bindings) {
    const tool = manifest.find(t => t.name === binding.tool);
    if (!tool) continue;

    const label = `${binding.class}.${binding.method}`;
    try {
      validateProjection(binding.returns.projection, tool.outputSchema, label);
      if (binding.cache) {
        // Cache projections validate against same output schema
        validateProjection(binding.cache.projection, tool.outputSchema, `${label} (cache)`);
      }
    } catch (err: any) {
      console.error(err.message);
      projectionErrors++;
    }
  }
  if (projectionErrors > 0) {
    console.error(`\n❌ ${projectionErrors} projection validation error(s). Fix domain-map.json.`);
    process.exit(1);
  }
  console.log("  ✓ All projections valid against output schemas");

  const manifestHash = sha256(manifestContent);
  const domainMapHash = sha256(domainMapContent);

  const header = fileHeader(manifestHash, domainMapHash);

  // Clean and recreate generated directory
  if (existsSync(GENERATED_DIR)) {
    rmSync(GENERATED_DIR, { recursive: true });
  }
  mkdirSync(GENERATED_DIR, { recursive: true });

  let fileCount = 0;

  // Generate a class file for each domain class
  for (const [className, config] of Object.entries(domainMap.classes)) {
    const classBindings = domainMap.bindings.filter(b => b.class === className);

    const classFileName = className.toLowerCase();
    const filePath = resolve(GENERATED_DIR, `${classFileName}.ts`);

    console.log(`  📄 ${classFileName}.ts (${classBindings.length} methods)`);

    // Collect return classes for imports (from bindings + factories)
    const returnClasses = new Set<string>();
    for (const b of classBindings) {
      if (b.returns.class && b.returns.class !== className) {
        returnClasses.add(b.returns.class);
      }
    }
    if (config.factories) {
      for (const f of config.factories) {
        if (f.returns !== className) {
          returnClasses.add(f.returns);
        }
      }
    }

    let code = header;

    // Imports
    code += `import type { StitchToolClient } from "../../src/client.js";\n`;
    code += `import { StitchError } from "../../src/spec/errors.js";\n`;

    for (const rc of returnClasses) {
      code += `import { ${rc} } from "./${rc.toLowerCase()}.js";\n`;
    }

    code += `\n`;

    // Class definition
    code += `/**\n * ${config.description}\n */\n`;
    code += `export class ${className} {\n`;

    // Constructor
    if (config.isRoot) {
      code += `  constructor(private client: StitchToolClient) {}\n`;
    } else {
      const ctorParams = config.constructorParams;
      // Declare fields
      for (const p of ctorParams) {
        code += `  public readonly ${p}: string;\n`;
      }
      code += `  public data: any;\n\n`;
      code += `  constructor(private client: StitchToolClient, data: any) {\n`;

      for (const p of ctorParams) {
        const fm = config.fieldMapping?.[p];
        if (fm) {
          if (fm.stripPrefix) {
            // Compute stripped value inline to avoid reassigning readonly
            const prefix = fm.stripPrefix;
            code += `    {\n`;
            code += `      let _v = typeof data === "string" ? data : data.${fm.from};\n`;
            code += `      if (typeof _v === "string" && _v.startsWith("${prefix}")) _v = _v.slice(${prefix.length});\n`;
            code += `      this.${p} = _v;\n`;
            code += `    }\n`;
          } else {
            code += `    this.${p} = typeof data === "string" ? data : data.${fm.from};\n`;
          }
          if (fm.fallback) {
            code += `    if (!this.${p} && typeof data === "object" && data.${fm.fallback.field}) {\n`;
            code += `      const parts = data.${fm.fallback.field}.split("${fm.fallback.splitOn}");\n`;
            code += `      if (parts.length === 2) this.${p} = parts[1];\n`;
            code += `    }\n`;
          }
        } else if (config.identifierField && p === ctorParams[0]) {
          code += `    this.${p} = typeof data === "string" ? data : data.${config.identifierField};\n`;
        } else {
          code += `    this.${p} = typeof data === "string" ? data : data.${p};\n`;
        }
      }

      code += `    this.data = typeof data === "object" ? data : undefined;\n`;
      code += `  }\n`;
    }

    // ID getter
    if (!config.isRoot && config.constructorParams.length > 0) {
      const idParam = config.idField || config.constructorParams[0];
      if (idParam !== "id") {
        code += `\n  /** Convenience alias for ${idParam} */\n`;
        code += `  get id(): string { return this.${idParam}; }\n`;
      }
    }

    code += `\n`;

    // Methods
    for (const binding of classBindings) {
      const tool = manifest.find(t => t.name === binding.tool);
      if (!tool) {
        console.warn(`  ⚠️  Tool "${binding.tool}" not found in manifest, skipping.`);
        continue;
      }

      const paramTypes = generateParamType(tool, binding.args);
      const returnTypeStr = binding.returns.class
        ? (binding.returns.array ? `${binding.returns.class}[]` : binding.returns.class)
        : (binding.returns.type || "any");

      code += `  /**\n`;
      code += `   * ${tool.description?.split("\n")[0].trim() || binding.method}\n`;
      code += `   * Tool: ${binding.tool}\n`;
      code += `   */\n`;
      code += `  async ${binding.method}(${paramTypes}): Promise<${returnTypeStr}> {\n`;

      // Cache check
      if (binding.cache) {
        const cacheExpr = emitCacheProjection(binding.cache.projection);
        code += `    // ${binding.cache.description}\n`;
        code += `    if (${cacheExpr}) return ${cacheExpr};\n\n`;
      }

      code += `    try {\n`;
      code += `      const raw = await this.client.callTool<any>("${binding.tool}", ${generateArgsObject(binding.args)});\n`;
      code += `      return ${generateReturnExpression(binding, className, domainMap)};\n`;
      code += `    } catch (error) {\n`;
      code += `      throw StitchError.fromUnknown(error);\n`;
      code += `    }\n`;
      code += `  }\n\n`;
    }

    // Factory methods (local constructors, no API call)
    if (config.factories) {
      for (const factory of config.factories) {
        const factoryClass = domainMap.classes[factory.returns];
        if (!factoryClass) {
          console.warn(`  ⚠️  Factory returns "${factory.returns}" but class not found, skipping.`);
          continue;
        }
        // Ensure import exists
        if (factory.returns !== className) {
          returnClasses.add(factory.returns);
        }
        code += `  /**\n`;
        code += `   * ${factory.description || `Create a ${factory.returns} from an ID.`}\n`;
        code += `   */\n`;
        code += `  ${factory.method}(id: string): ${factory.returns} {\n`;
        code += `    return new ${factory.returns}(this.client, id);\n`;
        code += `  }\n\n`;
      }
    }

    code += `}\n`;

    await Bun.write(filePath, code);
    fileCount++;
  }

  // Generate barrel export
  const indexPath = resolve(GENERATED_DIR, "index.ts");
  let indexCode = header;
  for (const className of Object.keys(domainMap.classes)) {
    indexCode += `export { ${className} } from "./${className.toLowerCase()}.js";\n`;
  }
  await Bun.write(indexPath, indexCode);
  fileCount++;

  console.log(`\n📦 Generated ${fileCount} files in core/generated/src/`);

  // Update stitch-sdk.lock
  const generatedHash = hashDirectory(GENERATED_DIR);
  let lock: any = {};
  try {
    lock = JSON.parse(await Bun.file(LOCK_PATH).text());
  } catch {
    lock = { schemaVersion: 1 };
  }

  lock.generated = {
    generatedAt: new Date().toISOString(),
    sourceHash: `sha256:${generatedHash}`,
    manifestHash: `sha256:${manifestHash}`,
    domainMapHash: `sha256:${domainMapHash}`,
    fileCount,
  };

  lock.domainMap = {
    generatedAt: new Date().toISOString(),
    sourceHash: `sha256:${domainMapHash}`,
    manifestHash: lock.manifest?.sourceHash || "unknown",
    classCount: Object.keys(domainMap.classes).length,
    bindingCount: domainMap.bindings.length,
  };

  await Bun.write(LOCK_PATH, JSON.stringify(lock, null, 2) + "\n");
  console.log(`🔒 Updated ${LOCK_PATH} (generated section)`);
  console.log(`\n✅ Stage 3 complete.`);
}

main().catch((err) => {
  console.error("❌ Generation failed:", err);
  process.exit(1);
});
