import { parseArgs } from "util";
import { mkdir, writeFile } from "fs/promises";
import { join } from "path";
import { stitch } from "@google/stitch-sdk";

// Parse command line arguments
const { values } = parseArgs({
  args: process.argv.slice(2),
  options: {
    projectId: { type: "string" },
    screenId: { type: "string" },
    prompt: { type: "string" },
    outDir: { type: "string", default: "./out" },
  },
});

async function run() {
  if (!values.prompt && !(values.projectId && values.screenId)) {
    console.error("Must provide either --prompt OR (--projectId AND --screenId)");
    process.exit(1);
  }

  let htmlUrl: string;

  if (values.prompt) {
    console.log(`Generating new project with prompt: "${values.prompt}"...`);
    const project = await stitch.createProject("Next.js App");
    console.log(`Created project ${project.id}`);
    const screen = await project.generate(values.prompt);
    console.log(`Generated screen ${screen.id}`);
    htmlUrl = await screen.getHtml();
  } else {
    console.log(`Fetching screen ${values.screenId} from project ${values.projectId}...`);
    const project = stitch.project(values.projectId!);
    const screen = await project.getScreen(values.screenId!);
    htmlUrl = await screen.getHtml();
  }

  console.log(`Downloading HTML from ${htmlUrl}...`);
  const response = await fetch(htmlUrl);
  if (!response.ok) {
    throw new Error(`Failed to download HTML: ${response.statusText}`);
  }
  const html = await response.text();

  console.log(`Creating output directory ${values.outDir}...`);
  await mkdir(values.outDir, { recursive: true });
  await mkdir(join(values.outDir, "app"), { recursive: true });

  // 1. Extract Tailwind Config
  console.log("Extracting Tailwind config...");
  const configMatch = html.match(/<script id="tailwind-config">([\s\S]*?)<\/script>/);
  let tailwindConfigCode = "import type { Config } from 'tailwindcss';\n\nexport default {\n  content: [\n    './app/**/*.{js,ts,jsx,tsx,mdx}',\n  ],\n  theme: { extend: {} },\n  plugins: [],\n} satisfies Config;";

  if (configMatch) {
    const rawConfig = configMatch[1];
    // Very naive extraction: attempt to grab the object after `tailwind.config = `
    const objMatch = rawConfig.match(/tailwind\.config\s*=\s*({[\s\S]*});/);
    if (objMatch) {
      // Just wrap it in the TS structure
      tailwindConfigCode = `import type { Config } from 'tailwindcss';\n\nconst config: Config = ${objMatch[1]};\nconfig.content = [\n  './app/**/*.{js,ts,jsx,tsx,mdx}',\n];\nexport default config;`;
    }
  }

  await writeFile(join(values.outDir, "tailwind.config.ts"), tailwindConfigCode);
  console.log("Wrote tailwind.config.ts");


  // 2. Extract Google Fonts
  console.log("Extracting Google Fonts...");
  const fonts = html.match(/<link[^>]*fonts\.googleapis\.com[^>]*>/g) ?? [];
  const fontLinks = fonts.join("\n    ");

  // 3. Extract Body content
  console.log("Extracting HTML body...");
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/);
  let bodyContent = bodyMatch ? bodyMatch[1] : html;

  // Convert generic HTML to JSX (naive for this script)
  // class -> className
  bodyContent = bodyContent.replace(/class=/g, "className=");
  // close inputs and img
  bodyContent = bodyContent.replace(/<img([^>]*[^\/])>/g, "<img$1 />");
  bodyContent = bodyContent.replace(/<input([^>]*[^\/])>/g, "<input$1 />");
  bodyContent = bodyContent.replace(/<br>/g, "<br />");
  bodyContent = bodyContent.replace(/<hr([^>]*[^\/])?>/g, "<hr$1 />");
  // remove unescaped script tags from body
  bodyContent = bodyContent.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "");

  const pageCode = `export default function Page() {\n  return (\n    <>\n${bodyContent}\n    </>\n  );\n}\n`;
  await writeFile(join(values.outDir, "app", "page.tsx"), pageCode);
  console.log("Wrote app/page.tsx");


  const layoutCode = `import './globals.css';\n\nexport const metadata = {\n  title: 'Stitch Next.js App',\n  description: 'Generated by @google/stitch-sdk',\n};\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <head>\n        ${fontLinks}\n      </head>\n      <body>\n        {children}\n      </body>\n    </html>\n  );\n}\n`;
  await writeFile(join(values.outDir, "app", "layout.tsx"), layoutCode);
  console.log("Wrote app/layout.tsx");

  const globalsCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n`;
  await writeFile(join(values.outDir, "app", "globals.css"), globalsCss);
  console.log("Wrote app/globals.css");

  // Next.js config to allow googleusercontent images if they exist
  const nextConfigCode = `/** @type {import('next').NextConfig} */\nconst nextConfig = {\n  images: {\n    remotePatterns: [\n      {\n        protocol: 'https',\n        hostname: 'lh3.googleusercontent.com',\n      },\n      {\n        protocol: 'https',\n        hostname: 'images.unsplash.com',\n      }\n    ],\n  },\n};\n\nmodule.exports = nextConfig;\n`;
  await writeFile(join(values.outDir, "next.config.js"), nextConfigCode);
  console.log("Wrote next.config.js");


  console.log(`\nDone! Next.js scaffolding written to ${values.outDir}`);
  console.log("Next steps:");
  console.log(`  cd ${values.outDir}`);
  console.log("  npm init -y");
  console.log("  npm install next react react-dom tailwindcss postcss autoprefixer");
  console.log("  npx tailwindcss init -p");
  console.log("  npm run dev");
}

run().catch(console.error);
